UKHomeOffice/acrs

- .drone.yml
We are updating the Image registry. Quay repository is being replaced with Amazon ECR
Quay has security risks because it is a public repository and could be accessed by the public. Amazon ECR is a private registry and hence more secure.
-  Drone.yaml has been updated with yaml for ECR added to the pipeline steps
- The yaml for quay has been replaced with ecr's yaml
- The AWS secrets to access aws and push the image to ecr has been added to Drone CI UI
- This branch is merged to master and then tested
-Several commits and PR will be raised to to test the pipeline 
- [] I have written tests (if relevant)
> Acrs 37 acrs registry update

- kube/hof-rds-api/deployment.yml
Update the hof-rds-api image to the latest pushed to quay. 
Update the LATEST_MIGRATION value in environment for the deployment to the latest created
See [ACRS-39](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-39).
This PR updates the RDS via a new migration adding a `verify_lookup` table (DOB, BRP, UAN). This will be pre-filled with verified users and will be queried at the point of user login to verify users of the form are genuine.
[Added new migration in hof-rds-api](https://github.com/UKHomeOffice/hof-rds-api/pull/29). This generates a new image.
During deployment to the updated image as created above and configured in this PR the migration will run and new table will be added to RDS
Migrate and rollback tested locally ok.
Data to be added to RDS manually.
here is an …
> ACRS-39: Update hof-rds-api image to one with the latest migrations for DB verification

- apps/verify/behaviours/get-dob-field-hint.js
- apps/verify/index.js
- apps/verify/translations/src/en/fields.json
Add a dynamic hint for the `date-of-birth` field between the `/sign-in-brp` and `/sign-in-uan` pages.
Both pages have a date of birth field that is the same datapoint and can be saved to session as the same value. however the message hint for BRP has more text than the one for UAN.
Adds a behaviour that works out if we are on the `/sign-in-brp` page and if it is it will add the extra text to the date of birth field hint
Tested locally 
> ACRS-14 Fix dob field hint

- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/views/confirm-referrer-email.html
What?
[ACRS-48 - Is this referrers email](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-48)
Add the `/confirm-referrer-email` page to the `acrs/` steps
Why?
The `/confirm-referrer-email` page is a requirement of the flow.
> ACRS-48 confirm referrer email

- .drone.yml
- bin/deploy.sh
- kube/hof-rds-api/ingress.yml
Changing external ingress for prod env in acrs to internal ingress
Also added the staging environment in the pipeline
This ingress is used for internal communication between pods and services and not from the browser
Staging is added to be able to deploy to staging environment 
For prod in ingress.yaml, the external ingresses have been changed to internal ingress 
- [ x] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ x] I have created a JIRA number for my branch
- [ x] I have created a JIRA number for my commit
- [x ] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
- [x ] Ensure drone builds are green …
> ACRS-20 : Changed external ingress in prod to internal ingress and added staging env

- .drone.yml
Comment out a line in the drone.yml file.
This text is not functional and should be a comment. It is possible that uncommented this is breaking the config and causing drone builds to fail before they start.
This will be tested by the pipeline succeeding from this PR branch
> Comment out text that may be breaking pipeline config

- apps/verify/translations/src/en/validation.json
[ACRS-102](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-102)
Add a validation message for cases where non-email format entries are made into the verify app's user-email field.
Without the validation message there is no context given to the user after an incorrectly formatted entry into this field for example a URL or other non-email format text
Update validation messages for the verify app in the user-email field.
> ACRS-102: Fix bug - Add validation message for invalid non-email entry into field

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
[ACRS-52](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-52)
Adds the "Are you referring a parent to come to the UK?" page to the form. 
Adds step, field, validations and copy text.
This page is required in the ACRS form. The page is within a conditional block, but does not have any conditional logic of its own except for the forking from the next step.
> ACRS-52: Add Are you referring a parent to come to the UK? page

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/parent-details.html
- apps/verify/behaviours/send-verification-email.js
- test/_unit/custom-validations.spec.js
[ACRS-41](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-41)
Adds the Steps fields, view and validations for the '/parent-details' page.
Adds a few unit tests for the custom validator added.
Parent details are added in an aggregator format up to a limit of two parents. These fields are those that are added to the aggregator with each parent.
Aggregation will be added with the '/parent-summary' page.
Page and validations work locally. New tests passing locally.
There is some logic that needs to add a number into the title of this page (the number of parents added so far in the aggregator to a limit of 2). As the aggregator code will be added with the parent-summary page this information is only placeholder code for now and no number is added to the page in the relevant spot.
here …
> ACRS-41 Set up parent-details page

- apps/acrs/behaviours/locals-18-flag.js
- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/additional-family.html
- apps/acrs/views/no-family-referred.html
[ACRS-84](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-84)
[ACRS-94](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-94)
[ACRS-60](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-60)
[ACRS-101](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-101)
Adds the 'do you want to refer additional family members (i.e. not parents, siblings, partners or direct children depending on age) pages for both over-18 and under-18 (18 cut off being 2003-08-23 for the sake of this form).
Adds the logic for additional warning message page with return link for if a person seemingly does not want to refer anyone at all but has got to this point in the form.
The additional family section covers family that the referrer may want to refer but that are not direct family …
> ACRS: 84, 94, 60, 101 - Add Additional family initial pages over-18/under-18 routes

- apps/acrs/behaviours/resume-form-session.js
[ACRS-118](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-118)
Fixed a bug where the BRP/UAN option that was signed in with does not occur in the options of the radio list to choose the referral to continue with in the case of multiple referrals being found for the login email address.
Also updated code so that the correct array item is used when a selection is made from the subsequent radio list of possible referrals.
This bug forces a user to use a different referral they had already been filling instead of the one they presumably signed in to complete. It is interfering with testing and is a high priority fix.
- Remove an extra filter for options with an ID (only referrals brought from the database contain one).
- When choosing which session to create and move forward with, …
> ACRS-118: Fix bug that stops the BRP/UAN signed in with from appearing in the referrals list

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/brother-or-sister-details.html
- assets/scss/app.scss
[ACRS-56](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-56)
[ACRS-58](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-58)
As the question page for "Are you referring a brother or sister to come to the UK?" and the subsequent details page for brothers and sisters if the answer was yes.
Adds step and field definitions, view, copy and validations.
The user can refer up to 100 brothers or sisters in their referral. These pages set up the design and basic routing to add brothers and sisters.
This update does not add the looping/aggregate behaviour. Additionally it does not add the 'brother or sister count' to track the number added to the form so far. This will also be added with the review page and aggregate behavior.
Tested validations and initial routing working ok …
> ACRS-56/58: Add brother or sister question and details pages

- apps/acrs/fields/index.js
- apps/acrs/translations/src/en/validation.json
[ACRS-122](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-122)
[ACRs-125](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-125)
Two bug tickets with identical issue - the date of birth of the added parent or partner for referral must check that they are above 18 from the present date.
A referred partner or parent must be over 18 years old from the current date
Added the 'over18' validator from HOF to both fields
Tested ok on local
> ACRS 122/125 Add over18 validation to add partner and add parent date of birth fields

- apps/acrs/index.js
Replace the next step for the full-name step from confirm to confirm-referrer-email
Confirm step that was moved up for testing pdf generation, this was corrected but has been over-risen by the latest merge
> Replace confirm step that was moved up for testing pdf generation

- apps/acrs/views/additional-family.html
As per [ACRS-107](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-107) Add the ACRS guidance link to the additional-family page where it links to explain 'exceptional circumstances'
This covers both over and under 18 versions of the page - referred to in the above ticket as ACRS-60 and ACRS-94
The page has a link to an external GovUK page explaining guidance for referrers in ACRS. This link was not available at the time of creating the page, so it is added now in this PR
Over and under 18 versions of text in this page is dynamically rendered, but this link will appear and is required regardless of the age of the referrer
> ACRS-107 Add guidance link to additional-family page

- apps/acrs/behaviours/limit-partners.js
- apps/acrs/behaviours/partner-summary.js
- apps/acrs/behaviours/summary-modify-change-link.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/views/partner-summary.html
[ACRS-66 18+ UK ROUTE - Create a 'Partner you are referring' summary page](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-66)
Adds the /partner-summary page with looping aggregator limit of 1.
The partner details have been included into the final summary page `/confirm` though it is not currently up to spec and will need to be revisited.
The aggregation or "many" pattern has been used to capture partner details even though the referral is restricted to a single partner to take advantage of the framework's summary behaviour.
Checked
> ACRS-66 Implement /partner-summary

- server.js
- test/_unit/server.spec.js
[ACRS-144](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-144) 
Remove the phase banner from the ACRS form
The phase banner contains the feedback link to a form where users can typically give feedback on the service.
The business team are concerned that users will attempt to use the feedback link and form to provide more sensitive referral context through this channel. As such they have asked for us to remove the link.
Removing the link from the settings in server.js (providing HOF with no link) disables the whole banner in the layout.html view in the HOF framework.
Tested locally and banner is removed.
Before:
After:
Leaving the banner intact but removing the feedback form link only would be much more complex as this part of the code is in the HOF framework. You could possibly …
> ACRS-144 Remove the phase banner from ACRS form

- apps/acrs/behaviours/limit-additional-family.js
- apps/acrs/behaviours/limit-family-in-uk.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/pages.json
- apps/acrs/views/family-in-uk-summary.html
[ACRS-139](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-139)
Fix additional family index not displaying properly when adding new additional family
Fix family in UK index not displaying properly when editing existing family members
Allowed family in UK aggregator to be cleared when 'no' is selected after initially selecting yes in the section intro.
Removed some old code that was reintroduced by accident in #75
Index number in the page title for the number of family member being updated/added under different situations was not being displayed properly. For additional family this was in add cases, for family in the Uk this was in editing an existing member.
Fixed a bad assignment of the local value for additional family members
Added missing logic that was present in other …
> ACRS-139 Fix page title indexing in additional-family-details and family-in-uk-details pages

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/confirm-your-email.html
- apps/acrs/views/your-email.html
[ACRS-114 Change the question wording on /confirm-your-email](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-114)
The path to this page is updated to `/confirm-your-email` (from '/confirm-referrer-email') so all internal references have also been updated.
> ACRS-114 Change the question wording on /confirm-your-email

- apps/verify/behaviours/validate-case-details.js
[ACRS-124](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-124)
Users of BRP signin (Format roughly RZ0000000 or RZX000000) may attempt to sign in with their brp in lowercase - for the letter portion at least.
Ensured HOF form validation on the `/sign-in-brp` page and subsequent comparison with database values in verification allows for this use-case.
Users may want to sign in with a BRP number in lowercase. The business team have asked us to attempt to allow this use-case.
Forcing the entered BRP (or UAN though in all digits this doesn't matter) into uppercase before comparison with the database values in the verify_lookup table (confirmed to be uppercase uniformly) allows us to have more lenient validation on the frontend (already existed) while still making sure the comparison …
> ACRS-124 Allow lowercase sign in for BRP users

- apps/acrs/index.js
[ACRS-128](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-128)
Add Save and exit button and behaviour to the form screen 'Can you provide a telephone number?'
This page should have the `SaveFormSession` behaviour and 'Save and exit' button so the user can exit the form at this point with session saved to database
Added necessary fields to `acrs/index.js`
Local page running after update:
> ACRS-128 Show save and exit button on 'Can you provide a telephone number?' screen

- apps/acrs/translations/src/en/fields.json
[ACRS-147](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-147)
Add a missing legend to fields.json so that it appears in the summary page.
Field label in summary was showing js object link but not proper copy.
> ACRS-147: Add missing legend for partner so it shows on summary pages

- apps/acrs/translations/src/en/validation.json
[ACRS-140 Error Message for URL /decision-postal-address](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-140)
Added validation string `notUrl`
> ACRS-140 add validation string

- apps/acrs/behaviours/check-email-token.js
- config.js
- db/get-token.js
- db/save-token.js
[ACRS-17](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-17)
Allow the value for 'sign-in-method' to move from the verify session into the acrs session, so that the value will appear in the daily report CSV.
Although the field exists in the CSV, the values are missing as they are not present in the ACRS session which is used to populate. This information is required in the CSV.
Add the value from the verify session to the token stored while the user verifies by email. Add `'sign-in-method'` to values that are not removed from the new session when it is cleaned.
Tested locally the value appears in CSV
Now that this value is in the ACRS session it could actually be used as the session 'id-type' value. However as the current implementation is working it seems unwise to make this …
> ACRS-17: Allow 'sign-in-method' to be brought from verify to acrs app session

- apps/acrs/behaviours/create-and-send-pdf.js
- apps/acrs/behaviours/submit.js
Stop the submit behaviour trying to send a 'referrer' receipt email to several different email addresses.
Remove the code from older project that gathers a series of email addresses to send the receipt to. Send only to the `'user-email'` as used to verify with the form in the first place.
For ACRS we only want to send two emails on submit - a referrer receipt and a caseworker receipt. We had an issue where adding an 'immigration advisor' email to a form submission would send a third email in ACRS. 
This code was copied from another project (IMA) where the equivalent of a referrer receipt is sent to a series of addresses if they were added in the form. The caseworker receipt is sent separately as part of the process.
- Removed the chunk of code in submit behaviour that gathers then stores …
> ACRS-175 Only send customer receipt email to the address used during verification

- apps/acrs/views/partials/head.html
- apps/verify/views/partials/head.html
De-index the ACRS form - [ACRS-166](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-166)
So that the form is not returned via browser searches
Add the following HTML files to override the default head.html in the framework, including the `<meta>` robots tag with the "noindex" content value:
- `acrs/views/partials/head.html`
- `verify/views/partials/head.html`
Tested locally and in branch
> ACRS-166: De-index ACRS form

- apps/acrs/translations/src/en/validation.json
[ACRS-121 validation maxlength](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-121)
Corrections to `maxlength` and `regex` validations for fields:
parent-evacuated-without-reason
partner-living-situation
partner-why-without-partner
child-living-situation
child-why-without-child
> ACRS-121 fix maxlength validation text

- apps/acrs/index.js
[ACRS-174](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-174) Save and Exit Button Missing on How-send-Decision Page
missing button 
- added save and exit button on th index.js page
Tested manually
> ACRS-174-Bugfix-missing-button

- apps/acrs/behaviours/family-in-uk-summary.js
[ACRS-146](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-146) - Remove all details of added child/family should navigate to main option Page
- changed the behaviour implementation
> ACRS-146 Bugfix family summary

- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/pages.json
[ACRS-169 summary x3 email](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-169)
Add the `/your-email` option and address fields to the summary page.
> ACRS-169 add /your-email to summary

- apps/acrs/translations/src/en/fields.json
- Postal address page - missing spacing between address 2 and (optional)
[ACRS-167](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-167) - Postal address page - missing spacing
- There is a missing spacing between '2' and '(optional)'
Added a space between the text
tested locally
> ACRS-167-Bugfix missing space

- apps/acrs/fields/index.js
Remove the `isPageHeading` property from the `'is-legal-representative-email'` field.
This field is the last in a set of fields in the page, and its label should not be used to create the page heading (H1) - there is already a H1 level element in this page generated elsewhere.
Removing this field stops the label from being rendered as an additional H1 in the page.
Before change (2 x H1):
After change (1 x H1):
> ACRS-154 Immigration Advisor Details page - remove additional H1

- apps/verify/translations/src/en/fields.json
Add a label to the `"user-email"` field in the verify app.
The lack of label test was showing the object link to where the label would be instead of the actual label text. This could confuse users of screen readers as it does not give adequate instructions for the field
Before label updated:
After label updated:
> ACRS-150: Add missing label to email address entry field in verify app

- apps/acrs/index.js
[ACRS-155 IA Switch Bug](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-155)
On `/information-you-have-given-us` page, when using the "Change" link of "Who is completing this form?",
the "Save and continue" button of `/who-completing-form` returned immediately to 
`/information-you-have-given-us` without the opportunity to add either a helper or immigration advisor.
This quick-fix for this was to add the `continueOnEdit` flag in the correct places to 
prevent `save-form-session` from immediately redirecting.
However, the `continueOnEdit` handling is not ideal for `/who-completing-form` which only requires 
onward editing for two of the three options.
The flaw in this quick-fix is that selecting "The referrer" option on `/who-completing-form` will 
unnecessarily re-visit …
> ACRS-155 fix switch IA to helper

- apps/acrs/fields/index.js
- apps/verify/fields/index.js
[ACRS-149](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-149)
Add `mixin: 'input-date'` to all date component fields.
Adding the mixin type to the date component fields fixes an issue where links moving focus from error summary to erroring field are broken in the case of dates.
This was reported as an accessibility issue.
> ACRS-149 Add mixin types to all date components in fields

- apps/acrs/index.js
- apps/acrs/translations/src/en/buttons.json
- apps/acrs/translations/src/en/errors.json
- apps/verify/translations/src/en/buttons.json
- apps/verify/translations/src/en/errors.json
[ACRS-70](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-70) - Change content of timeout message
To allow display a different timeout message rather than the defined hof framework message 
- Added error.json in the translation folder for both acrs and verify with the custom text
- 
Tested locally 
> ACRS-70 Change timeout message

- .snyk
- apps/verify/behaviours/send-verification-email.js
- apps/verify/translations/src/en/validation.json
[ACRS-103](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-103)
To allow error message display instead of 500 error page 
- Removed the default error in the catch block in the send verification behaviour file allow a custom error render
- Added error message in the validation.js
- 
Tested manually 
> ACRS-103 Bugfix Error message for email

- .snyk
- apps/acrs/behaviours/resume-form-session.js
- db/save-token.js
Fixed bug [ACRS-131](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-131) where if a user logs in to the form using a BRP number, has multiple referrals against their email address, then selects to continue with a form started with a UAN the app will throw an error.
Simplified the session creation behaviour so that it only pulls the latest referrals stored against a user (plus a new referral if relevant) rather than bringing back previous session stored data which is not needed.
Ensured that when a user selects a form the session data from login is overwritten by the stored data, so that login data for one referrer doesn't bleed into other referrers form data when switching between referrals.
The bug stops anyone who attempts to work on a referral that was originally started by …
> ACRS-131: Fix loading UAN based form when verified with BRP and vice versa

- apps/acrs/behaviours/aggregator-save-update.js
- apps/verify/behaviours/send-verification-email.js
[ACRS - 206](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-206) -  Emailed is sent to User even though there is error shown on the page
[ACRS - 134 ](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-134) - Family in the UK indexing issue
- Fixed bug for ACRS-206 when email is correct but display the error message and still send message  for gov notify. On line 98 of the send-verification-email.js behaviour i have changed the logic in the if block
- Fix the indexing for aggregator values when user click on change item and still retain it position. I have set two variable to hold the current index of item and if the item is updated 
tested on local machine
> ACRS-134 BugFix Family index

- .gitignore
- apps/acrs/behaviours/aggregator-save-update.js
- apps/acrs/behaviours/continue-report.js
- apps/acrs/behaviours/edit-route-return.js
- apps/acrs/behaviours/edit-route-start.js
- apps/acrs/behaviours/family-in-uk-summary.js
- apps/acrs/behaviours/limit-family-in-uk.js
- apps/acrs/behaviours/reset-summary.js
- apps/acrs/behaviours/save-form-session.js
- apps/acrs/behaviours/summary-modify-change-link.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/views/partials/summary-table.html
- test/_unit/edit-route-return.spec.js
- test/_unit/save-form-session.spec.js
[ACRS-185 Summary Change Routing](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-185)
This ticket address the problem of routing the looping sections from the Summary pages. When a user re-entered a looping section, for instance `/children` some of the routes would not return to the summary but would continue through the standard happy path.
This problem is addressed by providing two new behaviours that set-up and return-from a Change route by storing the return url in the session and checking for it when a loop section is complete. Additionally the urls for the Change links to the looping section "Question" (intro) page have been modified to prevent them from jumping straight into the sections -details pages.
An additional check for `no-family-referred` has been added to the …
> ACRS-185 Summary Change Routing

- .snyk
- apps/acrs/behaviours/additional-family-summary.js
- apps/acrs/behaviours/brother-sister-summary.js
- apps/acrs/behaviours/children-summary.js
- apps/acrs/behaviours/family-in-uk-summary.js
- apps/acrs/behaviours/parent-summary.js
- apps/acrs/behaviours/partner-summary.js
- apps/acrs/sections/summary-data-sections.js
[ACRS-218](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-218) - DOB Month Defaulting to January
The month of birth when entering family members in the form is defaulting to January. This needs to be checked on all family screens (parent, partner, brother/sister, children, additional family, family in UK) to ensure that the correct month of birth is saved
In each summary page there was an issue with the moment library for date format which prevent the original daate from formatting then setting it to default.
- I have removed the date format from each summary page behaviour to enable render the exact date
- Added 2 security vulnerabilities to .synk list
Tested locally
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093 …
> ACRS-218 Bugfix DOB Month defaulting

- apps/verify/views/content/accessibility.md
[ACRS-219](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-219)   Accessibility Statement - Link to Form Leading to Page not found
The first two link in the Accessibility Statement page not redirecting properly
- Added http:// to the link on markdown page
Tested locally 
> ACRS-219-Bugfix Link not working

- .snyk
- apps/acrs/behaviours/edit-route-return.js
- apps/acrs/behaviours/edit-route-start.js
[ACRS-216](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-216) - Check your answers page change link doesn't get updated for who is completing this form
-Upon selecting a new option, the displayed details should update to reflect the information associated with the new selection.
- Despite the change, the displayed details continue to show the information from the initial selection.
- Unset the value when different option is selected in the edit-route-return and edit-route-start.js file behaviour
- Add list of vulnerabilities to .synk file
Tested on local machine
> ACRS-216 Bugfix doesn't get updated

- kube/hof-rds-api/deployment.yml
* Using hof-rds-api image with hof-nodejs image and upgraded node packages
* Tested and replaced in all the remaining HOF services
* Fixed vulnerabilities in the image
* Testing in Branch env
* https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1179
* Large number of Critical and High CVE Vulnerabilities have been detected by Trivy Scan
* This image has fixed the vulnerabilties
* Drone build with Trivy scan report, https://drone-gh.acp.homeoffice.gov.uk/UKHomeOffice/hof-rds-api/223
* Replace hof-rds-api image with latest
* Add a comment to explain the version and Date.
* Regression testing in Branch and then merge to master to deploy and test in UAT, Stage and promote to Prod
* Check boxes will ticked as we pass through each env
* Drone build is successful
* Pods are Healthy
* …
> HOFF-1179: Update hof-rds-api image to latest v3.1.0

- package.json
- yarn.lock
[HOFF-1271](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1271) Criticals need updating in the node packages
We could use the upgraded base image.
Remediate Critcal Vulns
Using resolutions to upgrade to specific versions
> HOFF-1271-Criticals update

- .drone.yml
The final step has a depends up
This pull request introduces a dependency update in the Drone CI pipeline configuration, specifically for the production deployment workflow. The change ensures that the `promote` step for the `PROD` target waits for the `clone_repos_prod` step to complete before executing.
To fix release issue
Pipeline dependency update:
* [`.drone.yml`](diffhunk://#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7R403-R404): Added `depends_on: - clone_repos_prod` to the `promote` step for the `PROD` target, enforcing correct step execution order in the CI/CD pipeline.
*
> adding depends on to allow the prod deploy step
