- .drone.yml
*comment out staging environmen
*until it's namespace is created
Commenting out staging env.
It's namespace and secrets have not yet been created
commenting out staging yaml code within the pipeline steps
N/A
- [X ] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ X] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
- [ X] Ensure drone builds are green especially tests
- [ X] I will squash the commits before merging
> ACRS-Update the staging yaml files

- .drone.yml
I add the production URL domain name to drone.yml and fix a comment in the file pointing out to the UAT that was the branch environment 
The production URL was pending to be sing off by the stakeholders and the file was created before knowing the domain name. Also, as it is a small changed to familiarize myself with the pull request HO ways of working.
By replacing the commented out production name by the actual name
N/A
N/A
N/A
> ACRS-20: Add production url

- apps/acrs/behaviours/check-email-token.js
- apps/acrs/behaviours/resume-form-session.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/buttons.json
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/select-form.html
- apps/acrs/views/start.html
- config.js
[ACRS-61](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-61)  Which form are you completing
To allow user to select form the which to continue with if they have multiple form that are un-submitted.
- Modified the resume-form-session.js file to filter between the uan and brp number and create radio buttons
- Added header for the select form  and start page
- Added select-form and start page in html
- Added validation for the radio button in validation.json file
Tested locally 
> ACRS 61 Which form you completing

- apps/acrs/behaviours/continue-report.js
- apps/acrs/behaviours/save-and-exit.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- config.js
[ACRS-15](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-15) Save and Exit (returning user feature)
The save and exit functionality exists on several pages throughout the form. it helps user and save the current form and return in future to continue 
- Added save and exit behaviour functionality to allow user to Save and Exit form when user decides to continue later in 
save-and-exit.js file
- Merged ACRS- 61 and ACRS-35 branch to display and test if they work ok 
- Added html pages to inform user the details has been saved
Tested on my local machine 
> Acrs 15 save and exit

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- config.js
- lib/utilities.js
- test/_unit/lib/utilities.spec.js
What?
[ACRS-47 - What is your full name](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-47)
Adds the `/full-name` page to the `acrs/` steps
Why?
The `/full-name` page is a requirement of the flow.
> Acrs 47 full name

- apps/acrs/behaviours/continue-report.js
- apps/acrs/behaviours/save-form-session.js
- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/immigration-adviser-details.html
- apps/acrs/views/partials/legal-representative-email-details.html
- config.js
[ACRS-46](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-46) Immigration Adviser details
To provide details of an immigration adviser
- Added partial page for legal immigration email in partial folder
- Added fields types in the fields/index.js
- Added field text -Added validation for each required field on immigration details page 
Tested on local machine 
> ACRS-46 Immigration adviser details

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
[ACRS-49 Does the referrer have an email](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-49)
Add the `/referrer-email` page to the `acrs/` steps
Checked
> ACRS-49 Implement /referrer-email

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
[ACRS-50 Can you provide a telephone number](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-50)
Add the `/provide-telephone-number` page to the `acrs/` steps
Checked
> ACRS-50 Implement /provide-telephone-number

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
[ACRS-42 Create 'Partner's details' page](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-42)
Add the `/partner-details` page to the `acrs/` steps
Checked
> ACRS-42 Implement /partner-details

- .drone.yml
- bin/deploy.sh
- kube/app/deployment.yml
- kube/cron/hof_db_table_replacer.yaml
- kube/file-vault/file-vault-deployment.yml
- kube/hof-rds-api/deployment.yml
- kube/hof-rds-api/ingress.yml
Updated the names of RDS and S3 buckets
To match the names of the new resources created in staging env.
Changed to new names indicated on the acp request tickets
- [ X] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [X ] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
- [ X] Ensure drone builds are green especially tests
- [ X] I will squash the commits before merging
> Acrs rdss3 names update

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/views/children.html
[ACRS-57 Implement /children](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-57)
Add the `/children` page to the `acrs/` steps
Checked
> ACRS-57 Implement /children

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/content/family-live-in-uk.md
- apps/acrs/views/family-in-uk.html
[ACRS-86](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-86) - FAMILY IN UK
To allow user completing additional family members section to add family living in UK
- Added family live in the UK page
- Added fields for family live in the UK for Yes or No
- Added validation for field
- Added a markdown page to display text on the family live in uk page
Tested on local machine 
> ACRS 86 Family live in UK

- kube/file-vault/file-vault-deployment.yml
* changed secret name file vault
updated s3 bucket's secret name
pods failing due to incorrect secret name
updated in the code and raise a PR
- [ X] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ X] I have created a JIRA number for my branch
- [X ] I have created a JIRA number for my commit
- [ X] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
- [X ] Ensure drone builds are green especially tests
- [ X] I will squash the commits before merging
> ACRS-20: Update secrets in File-vault

- apps/acrs/behaviours/children-summary.js
- apps/acrs/behaviours/limit-children.js
- apps/acrs/behaviours/summary-modify-change-link.js
- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/child-details.html
- apps/acrs/views/children-summary.html
[ACRS-59 Create 'Child's details' page](https://collaboration.homeoffice.gov.uk/jira/browse/ABCD-59)
[ACRS-69 Create a 'Children you are referring' summary page](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-69)
Adds the /child-details & /children-summary pages with looping aggregator limit of 100.
> ACRS-59 ACRS-69 Implement /child-details /children-summary

- apps/acrs/behaviours/exit-to-sign-in.js
- apps/acrs/index.js
- apps/acrs/views/information-you-have-given-us.html
- assets/scss/app.scss
[ACRS-111 Change Exit button behaviour /information-you-have-given-u](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-111)
Adds an Exit button to page and when clicked clears the session and redirects user to `/sign-in`
Checked
> ACRS-111 Change Exit button behaviour /information-you-have-given-u

- apps/acrs/behaviours/create-and-send-pdf.js
- config.js
Updates to match changes to the customer receipt template
New fields were added to the customer receipt template that was breaking notify emails
Added the new fields to notify personalisation for customer receipt.
local, branch and UAT
> Updates to match changes to the customer receipt template

- apps/acrs/behaviours/exit-to-sign-in.js
- apps/acrs/index.js
[ACRS-112 Change Exit button behaviour on /select-form](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-112)
Add the Exit button functionality to the `/select-form` page. Exit redirects to `/sign-in`.
Checked
> ACRS-112 Change Exit button behaviour on /select-form

- apps/acrs/fields/index.js
- apps/acrs/index.js
- apps/acrs/translations/src/en/fields.json
- apps/acrs/translations/src/en/pages.json
- apps/acrs/translations/src/en/validation.json
- apps/acrs/views/your-email.html
[ACRS-113 Change the question wording on /your-email](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-113)
The path to this page is updated to `/your-email` (from '/referrer-email') so all internal references have also been updated.
The updated text is added to the page using a standard html template.
> ACRS-113 Change the question wording on /your-email

- apps/acrs/fields/index.js
- apps/acrs/translations/src/en/validation.json
[ACRS-117 url validation /full-name](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-117)
`/full-name` added `notUrl` validation
> ACRS-117 Add notUrl validation

- apps/acrs/translations/src/en/validation.json
[ACRS-136 country validation text](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-136)
fixed for:
/parent-country
/brother-or-sister-country
/partner-country
/child-country
> ACRS-136 fix Country validation text

- apps/acrs/behaviours/declaration.js
- apps/acrs/fields/index.js
- apps/acrs/translations/src/en/validation.json
- config.js
[ACRS-137 dob validation /child-details](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-137)
Added the `isUnder18` validation to the /child-details date-of-birth field. dob is configured from `dobCutoff`
> Acrs 137 dob validation child

- apps/acrs/index.js
- config.js
Fix 500 error due to missing template id and missing sections and behaviours before submit
The submit behaviour has been moved declaration from confirm, there are is data to submit and the failed submission id was missing
> Fix 500 error due to missing template id and missing sections and behaviours before submit

- apps/acrs/behaviours/declaration.js
- config.js
- lib/utilities.js
[ACRS-152](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-152) - Declaration page logic for under/over 18
Should check if the any added members is under / over 18 at the time of submission so it can direct then to the appropriate declaration page
- Implement function to check for applicant under and over 18 at the submission of an application.
- Added age limit setting in the config.js file
- Code refactoring
Tested manually
> ACRS-152 Refactor logic for declaration

- apps/verify/translations/src/en/fields.json
> ACRS-162 update hint text

- apps/acrs/behaviours/declaration.js
- apps/acrs/translations/src/en/pages.json
- apps/verify/index.js
- apps/verify/views/accessibility.html
- apps/verify/views/content/accessibility.md
- assets/scss/app.scss
- config.js
- hof.settings.json
- server.js
- test/_unit/server.spec.js
[ACRS-54](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-54) - ACRS - Update Accessibility Statement
To enable user read the Accessibility statement
_ Added template for accessibility in verify folder of view section to enable render a. customised accessibility page
- set getAccessibility to true not to render the default accessibility page
- Added the path in Verify/index.js
- Renamed a variable for consistency
- Added css styling to accessibility .html page
tested on local machine 
> ACRS 54 Update accessibility state

- apps/acrs/behaviours/summary-modify-change-link.js
- apps/acrs/sections/summary-data-sections.js
- apps/acrs/translations/src/en/pages.json
[ACRS-105 summary page](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-105)
The final Summary Page `/confirm` has been brought into aligment with the figma. Some additional changes to the layout were implemented with agreement of the UCD team.
Both the `/confirm` and `/information-you-have-given-us` pages use the same layout function and produce similar results. The figma shows different headings for use on these two pages. Again it was agreed with the UCD  to use the `/confirm` page headings for both.
> ACRS-105 summary page

- apps/acrs/sections/summary-data-sections.js
[ACRS-180 Summary page ordering](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-180)
Reorder the partner and children questions on the summary page
> ACRS-180 Reorder questions on Summary

- apps/acrs/behaviours/submit.js
[ACRS-178 PDF referrer details](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-178)
Disable section sorting during html render
> ACRS-178 disable sorting

- apps/verify/translations/src/en/pages.json
- apps/verify/views/accessibility.html
[ACRS-184 Page title missing for Accessibility Statement](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-184)
Added `<title>`
> ACRS-184 Add accessibility <title>

- .snyk
- apps/acrs/behaviours/resume-form-session.js
- apps/acrs/behaviours/save-form-session.js
- apps/acrs/index.js
- apps/verify/behaviours/send-verification-email.js
[ACRS-225](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-225) - Issue with user being unable to access their Referral form
Despite users are registered and have un-submitted application, it denied user access 
- Code refractory and modify the send verification-email.js to allow users with correct email login.
- Tested locally 
- 
> Acrs 225 bugfix no access to users

- kube/file-vault/file-vault-deployment.yml
* Fixed vulnerabilities in the image in file-vault
* Large number of Critical and High CVE Vulnerabilities have been detected by Trivy Scan
* Updated node
* Add a comment to explain the version and Date.
* Smoke tests done on ASC, received notification
* Regression testing in Branch and then merge to master to deploy and test in UAT, Stage and promote to Prod
* Check boxes will ticked as we pass through each env
* Drone build is successful
* Pods are Healthy
* Staging environment has been commented out in pipeline 4 years ago by team
> ACRS-277-Upgrading service to use new filevault image v3.0.0
